name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    uses: sgnl-actions/.github/.github/workflows/ci.yml@825ee4ad2c6eb413ed19a65ff9faec19e1eded35 # v1.4.0
